### ISSUE TITLE
[BUG]: (MDA Reference App/Breadcrumb Page) Width constantly shrinks when resized

### ISSUE THREAD

**Issue by scottdurow** [microsoft/powercat-creator-kit#100]
**Describe the bug**
When the breadcrumb 

**To Reproduce**
1. Open the model-driven reference app
2. Navigate to the breadcrumb page
3. Change the width slider as shown below

**Expected behavior**
The breadcrumb component should grow and shrink with items moving in/out of the overflow, however it constantly shrinks to all items in the overflow

**Screenshots**
![Breakcrumb width](https://user-images.githubusercontent.com/2871121/189001329-7091a3e5-9a57-4531-b615-80f98c3c1acb.gif)

**Additional context**
This only happens inside the player - not Power Apps studio.

**Comment by mikefactorial** [comment]
@scottdurow This has been fixed in the latest release.
