### ISSUE TITLE
[Creator Starter Kit] BUG:

### ISSUE THREAD

**Issue by prashanthisiddu** [microsoft/powercat-creator-kit#103]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by slaouist** [comment]
I am not seeing the issue here ?

**Comment by denisem-msft** [comment]
Closing this as there is no content.
