### ISSUE TITLE
Add searchable Combo Box component

### ISSUE THREAD

**Issue by pstrindlund** [microsoft/powercat-creator-kit#104]
One large issue with the FluentUI version of the Combo Box is that it's missing the "SearchText" property. It would be awesome if the Creator Kit contained a, searchable, Combo Box component that has the functionality to get to the search text inside the control.

See: https://powerusers.microsoft.com/t5/Power-Apps-Ideas/Power-Apps-Fluent-UI-ComboBox-Functionality/idi-p/1328988

**Comment by denisem-msft** [comment]
Thanks for the feedback @pstrindlund - we've forwarded this feedback to the product team. We will take this into consideration based on resource availability.
