### ISSUE TITLE
[Feature] Fluent UI Button is missing as a component although it has been used in creator kit reference app

### ISSUE THREAD

**Issue by dipteshbose** [microsoft/powercat-creator-kit#106]
**Is this request for a new component, or additional functionality for an existing component? **
Additional

**Have you validated that your desired feature or component is not already in the [backlog](https://github.com/microsoft/powercat-creator-kit/issues?q=is%3Aopen+is%3Aissue+label%3Abacklog)?**

**Describe the component and functionality you would like to see in the starter kit**
Fluent UI Button is missing as a component although it has been used in creator kit reference app

**Describe alternatives you've considered**
I have exported the components from creator kit reference app, imported the components in my canvas app and then copied and pasted the Fluent UI button by unpacking / editing the component.

**Additional context**
New Button has "Button Type" property which the standard button doesn't

![image](https://user-images.githubusercontent.com/65800453/189487152-2c450a70-6f06-4756-9794-0f7994433e6f.png)

**Comment by scottdurow** [comment]
Hi @dipteshbose,
This button is part of the out-of-the-box controls available on custom pages (as part of model-driven apps) - it was copied and pasted from a custom page into the reference canvas-app.

**Comment by denisem-msft** [comment]
Closing this as there is no resolution we can provide aside from the response @scottdurow gave - the new Fluent UI button is only available in the canvas app and is not a Creator Kit component.
