### ISSUE TITLE
[Feature] Creator Kit Figma and Adobe XD kits

### ISSUE THREAD

**Issue by dipteshbose** [microsoft/powercat-creator-kit#107]
**Is this request for a new component, or additional functionality for an existing component? **
New Component

**Have you validated that your desired feature or component is not already in the [backlog](https://github.com/microsoft/powercat-creator-kit/issues?q=is%3Aopen+is%3Aissue+label%3Abacklog)?**

**Describe the component and functionality you would like to see in the starter kit**
Creator Kit / Fluent UI Figma and Adobe XD kits

**Describe alternatives you've considered**

**Additional context**

**Comment by denisem-msft** [comment]
Hi @dipteshbose, can you please provide more detail on this feature request?

If you are looking for a Figma kit with Fluent UI, the Fluent team has that available: https://www.figma.com/community/file/836828295772957889

**Comment by denisem-msft** [comment]
@dipteshbose please confirm if the Fluent UI Figma Kit is sufficient.

**Comment by dipteshbose** [comment]
yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
