### ISSUE TITLE
Tootltip in ExpandMenu

### ISSUE THREAD

**Issue by Juromudu** [microsoft/powercat-creator-kit#110]
ExpandMenu
I believe that tooltip in expandmenu (over each option) could be important

Thanks

**Comment by slaouist** [comment]
Fixed. Will be in Oct release. @Juromudu

**Comment by Juromudu** [comment]
Excellent. Thanks 
     

-----Mensaje original-----

De: Mehdi ***@***.***>
Para: microsoft ***@***.***>
CC: Juromudu ***@***.***>; Mention ***@***.***>
Fecha: viernes, 30 de septiembre de 2022 9:43 -05
Asunto: Re: [microsoft/powercat-creator-kit] Tootltip in ExpandMenu (Issue #110)

 

  Fixed. Will be in Oct release. @Juromudu —
