### ISSUE TITLE
[BUG]: How to render SharePoint People Picker Columns DisplayName Value

### ISSUE THREAD

**Issue by schneika** [microsoft/powercat-creator-kit#111]
**Describe the bug**
How to render SharePoint People Picker Columns DisplayName Value. i always get the whole OData-PeoplePicker-Object

**To Reproduce**
please see screenshot

**Expected behavior**
Want to show only the DisplayName of the User

**Screenshots**
![BasicListPeoplePickerDisplayname](https://user-images.githubusercontent.com/11440416/189984125-f4f268ed-e378-4779-ba5a-f6e3c059f41a.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10/11
 - Browser. Edhe Chromium

**Comment by DavesTechTips** [comment]
I am having the same issue on my side.

**Comment by scottdurow** [comment]
Hi @schneika,
One possible solution to this would be to use `AddColumns`.
Imagine if you had a sharepoint datasource `Items` with a column `Owner`
1. Change the DetailsList Items datasource to be: `AddColumns('Items',"OwnerName",Owner.DisplayName)`
2. Add the new `OwnerName` column to the Datasource Fields in the DetailsList properties
3. Update the `Columns` definition to use the new `OwnerName` column

Would this work for you?
Thank you for helping with the Creator Kit!

**Comment by schneika** [comment]
@scottdurow Ahhh! Very good idea! I have tried ClearCollect-Collection-Variables with AddColumns but this doesnt work.

Your suggestion is fine, i must AddColumns the Columns-Values directly to the SharePoint Datasource (Colelction not working for me) and have to restart the App because of a "Control not loading".
After App Restart all Columns Working  

Example:
Items=
SortByColumns(Filter(AddColumns(Datasource,"UserDisplayName", ensUser.DisplayName,"ManagerDisplayName", ensManager.DisplayName,"BusinessUnitValue", ensBusinessUnit.Value,"DivisionValue", ensDivision.Value,"StatusValue", ensStatus.Value,"State", ensState,"IDValue", ID,"JobRoleValue", ensJobRole.Value,"CountryValue", ensCountry.Value),StartsWith(Title, SearchBoxTestForm.SearchText)), "Title", If(varSortFilesAsc, Descending, Ascending))_

**Comment by scottdurow** [comment]
Hi @schneika - That's great. 
I've created an enhancement in the backlog to make this easier in future releases.

If this is a workable solution for you at this time - could I ask that you close this issue as resolved?
Thank you!

**Comment by scottdurow** [comment]
Just a note about this - to ensure that your queries are delegable, when you use AddColumns - do it on the outside of the Sort and Filter - that way, the sorting and filtering will be done on the server (if possible) and then the data will be added after it is retrieved.
