### ISSUE TITLE
[QUESTION]: Creator Kit does not show up in Power Platform CLI

### ISSUE THREAD

**Issue by rajyraman** [microsoft/powercat-creator-kit#115]
I wanted to try installing Creator Kit from AppSource using _pac application install_, but _pac application list_ does not list the Creator Kit solution. Below are the only solutions listed for my environment.

|FriendlyName                                              | UniqueName                          |
|-|-|
|AI Builder for Project Cortex                             | SharePointFormProcessing            |
|Banking customer intelligence                             | BankingCustomerIntelligenceAnchor   |
|Business Central Virtual Table (Preview)                  | MicrosoftBusinessCentralVEAnchor    |
|CCI Bots                                                  | msdynce_CustomerCareIntelligenceBots_Anchor|
|Customer Insights App                                     | msdyn_CustomerInsightsAnchor        |
|Customer Insights App User Management Prod                | CustomerInsights_FirstPartyAppUserManagementProd|
|Customer Insights App User Management Tip                 | CustomerInsights_FirstPartyAppUserManagement|
|Customer Insights App User Management Tip                 | CustomerInsights_FirstPartyAppUserManagementTip|
|Customer Insights customer card add-in (Preview)          | CustomerInsightsCustomerCard        |
|Customer Service Team Member                              | msdynce_CustomerServiceTeamMemberAnchor|
|CVAA Solution                                             | msdynce_EmailInUnifiedInterface     |
|Dual-write Application Core Solutions                     | msdyn_DualWriteAppCoreAnchor        |
|Dual-write application orchestration solution             | Dynamics365FinanceAndOperationsAnchor|
|Dual-write Asset Management Solutions                     | msdyn_DualWriteAssetManagementAnchor|
|Dual-write core solution                                  | DualWriteCoreAnchor                 |
|Dual-write Dynamics 365 Human Resources                   | msdyn_Dynamics365HCMAnchor          |
|Dual-write Finance Solutions                              | msdyn_Dynamics365FinanceExtendedAnchor|
|Dual-write Notes Solutions                                | msdyn_Dynamics365NotesAnchor        |
|Dual-write Party and Global Address Book Solutions        | Dynamics365GABParty_Anchor          |
|Dual-write Supply Chain solution                          | msdyn_Dynamics365SupplyChainExtendedAnchor|
|Dynamics 365 Automotive Accelerator                       | MicrosoftCommonDataModelforAutomotive|
|Dynamics 365 Automotive Accelerator Portal                | AutoPortalAnchor                    |
|Dynamics 365 Export to Data Lake                          | msdyn_ExportToDataLakeAnchor        |
|Dynamics 365 for Field Service                            | FieldService_Anchor                 |
|Dynamics 365 for Project Service Automation               | ProjectService_Anchor               |
|Dynamics 365 FSI Loan Onboarding Sample Data              | LoanOnboardingSampleData            |
|Dynamics 365 Global Inventory Accounting                  | msdyn_GlobalInventoryAccountingAnchor|
|Dynamics 365 Global Inventory Accounting                  | msdyn_CostAccountingServiceAnchor   |
|Dynamics 365 HR Common Tables                             | HCMCommonAnchor                     |
|Dynamics 365 HR Virtual Tables                            | MicrosoftOperationsHRVEAnchor       |
|Dynamics 365 Inventory Visibility                         | msdyn_InventoryServiceAnchor        |
|Dynamics 365 Marketing Application                        | MicrosoftDynamics_MktPlaceholder2AnchorSolution|
|Dynamics 365 Marketing Application                        | MicrosoftDynamics_StandardDataAnchorSolution|
|Dynamics 365 Marketing Application                        | MicrosoftDynamics_LinkedInLeadGenAnchorSolution|
|Dynamics 365 Marketing Application                        | MicrosoftDynamics_PortalDataAnchorSolution|
|Dynamics 365 Marketing Application                        | DynamicsMKT_AnchorSolution          |
|Dynamics 365 Marketing Application                        | MicrosoftDynamics_VocLinkAnchorSolution|
|Dynamics 365 Marketing Application                        | SMBMarketingDemoData                |
|Dynamics 365 Marketing Application                        | MicrosoftDynamics_MktCompleteAnchorSolution|
|Dynamics 365 Media - Fan Engagement Apps                  | MediaAnchor                         |
|Dynamics 365 Media Content Production Management          | MediaContentProductionManagementAnchor|
|Dynamics 365 Media Portal                                 | MediaPortalAnchor                   |
|Dynamics 365 Nonprofit Accelerator                        | NonprofitCoreAnchor                 |
|Dynamics 365 Productivity Tools                           | ProductivityToolsAnchor             |
|Dynamics 365 Project Operations Demo Data                 | msdyn_ProjectOperationsSampleData_Anchor|
|Dynamics 365 Sales Insights Add-On                        | SalesInsightsAddOn                  |
|Dynamics 365 Sales, Enterprise Edition App                | msdyn_SalesApp                      |
|Dynamics 365 Service Scheduling                           | msdynce_CoreServiceSchedulingAnchor |
|Dynamics 365 Service scheduling migration                 | msdynce_CSSMigrationAnchor          |
|Dynamics 365 Telecommunications Accelerator               | TelcoAnchor                         |
|Education Solution - Higher Ed Apps                       | EducationAnchorHigherEd             |
|Education Solution - Higher Ed Marketing Data             | HigherEdMarketingSampleDataAnchor   |
|Education Solution - Higher Ed Students Portal            | EducationAnchorHigherEdEduPortal    |
|Education Solution - K12 Apps                             | EducationAnchorK12                  |
|Education Solution - K12 Students Portal                  | EducationAnchorK12EduPortal         |
|Finance + Operation Managed Data Lake                     | msdyn_FnoIntegrationMDLApp_Anchor   |
|Finance and Operations Virtual Entity                     | MicrosoftOperationsVEAnchor         |
|Financial services common sample data                     | FinancialServicesCommonSampleData   |
|Government Solution - Data Model                          | GovernmentCDMAnchor                 |
|Government Solution - Government Services App             | GovernmentServicesAppAnchor         |
|Government Solution - Government Services Sample Data     | GovernmentServicesSampleDataAnchor  |
|Government Solution - Portal                              | GovernmentPortalAnchor              |
|HCM Talent                                                | msdyn_TalentApp_Anchor              |
|Healthcare FHIR Common Data Model                         | FHIRAnchor                          |
|Intelligent Appointments                                  | IntelligentAppointmentsAnchor       |
|Intelligent Appointments Dependencies                     | IntelligentAppointmentsDependenciesAnchor|
|Intelligent Appointments Sample Data                      | IntelligentAppointmentsSampleData   |
|Intelligent Order Management Portal                       | msdyn_IOMOrderReturnsPortalAnchor   |
|Live Assist for Microsoft Dynamics 365                    | LiveAssistByCafeX                   |
|Live Assist for Microsoft Dynamics 365                    | LiveAssistByCafeXUSD                |
|Microsoft Check-ins                                       | SampleAnchor                        |
|Microsoft Check-ins                                       | msmwt_MicrosoftCheckins             |
|Microsoft Dynamics 365 - Gamification [DEPRECATED]        | Gamification                        |
|Microsoft Dynamics 365 - Organization Insights            | OrganizationInsightsSolution        |
|Microsoft Dynamics 365 CRM Hub                            | msdynce_CRMHub                      |
|Microsoft Dynamics 365 Project Operations                 | ProjectOperations_Anchor            |
|Microsoft Flow Extensions                                 | MicrosoftFlowExtensionsAnchor       |
|Microsoft Quick Reports                                   | MicrosoftQuickReports               |
|OData v4 Data Provider                                    | ODatav4DataProvider                 |
|Office365Groups                                           | Office365Groups                     |
|Omnichannel Power Virtual Agent Extension                 | OmnichannelPrimePVAExtensionAnchor  |
|Planning Optimization Add-in for Dynamics 365 SCM         | msdyn_MasterPlanningAnchor          |
|Power Apps Actions                                        | PowerAppsActions_Anchor             |
|Power Apps Checker                                        | msdyn_PowerAppsCheckerAnchor        |
|Power Automate document automation base kit               | Documentautomationbasekit           |
|Power BI Extensions (Preview)                             | msft_PowerBI_Anchor                 |
|Power Platform Employee Ideas App                         | MSFT_EmployeeIdeas                  |
|Power Platform Issue Reporting App                        | MSFT_IssueReporting                 |
|Retail banking core sample data                           | RetailBankingCoreSampleData         |
|Retail banking data model                                 | RetailBankingDataModelAnchor        |
|Telco Solution - Plant Maintenance Sample Data            | TelcoPlantMaintenanceSampleDataAnchor|
|Telco Solution - Sales Sample Data                        | TelcoSalesSampleDataAnchor          |
|Virtual connectors in Dataverse                           | msft_ConnectorProvider              |
|Virtual connectors in Dataverse                           | msft_ConnectorProviderAnchor        |
|Wrap for Power Apps                                       | msdyn_MobileAppsSolutionAnchor      |

**Comment by devkeydet** [comment]
It's there now.  Must be some sort of delay in how the list propagates.
