### ISSUE TITLE
[BUG]: Fluent UI Icons are out of date

### ISSUE THREAD

**Issue by P3N-101** [microsoft/powercat-creator-kit#116]
Icons are out of date, for example using the PowerApps icon in Pivot give you 
![image](https://user-images.githubusercontent.com/70491094/191021860-820ef5fc-0149-4934-abd5-71f5d1be5db2.png)

Is it possible to have consistent use of icons and the ability to change to an SVG as per DetailsList or at least make sure the Icons are the latest...

**Comment by denisem-msft** [comment]
@P3N-101 These are referring to the [Fluent UI icons library](https://developer.microsoft.com/en-us/fluentui#/styles/web/icons]. Please refer to that library to reference the corresponding icon that Creator Kit components will render. According to that library, the icon for "PowerApps" is correct in your screenshot.

**Comment by P3N-101** [comment]
Whilst you are correct, it doesn't make it right, the Icon is still out of date.  Its the old product icon... inconsistent with Microsoft branding at the very least.  How do we get the icon updated, or can we use our own SVG icons... that would be better and more consistent with other controls, like the details list
