### ISSUE TITLE
[BUG]: Picker control - Documentation is not correct (Fix is provided too)

### ISSUE THREAD

**Issue by formsandflows** [microsoft/powercat-creator-kit#118]
**Describe the bug**
https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/picker

The documentation talks about "TagDisplayName" and "SuggestionDisplayName". An s is missing. It must be "TagsDisplayName" and "SuggestionsDisplayName" to work.

**To Reproduce**
1. Create a canvas app
2. Add a button with the following code as shown below.
3. Add the "tagsPicker" code control.
4. Add **coll_Tags** to the property "items(items)". Add **coll_TagSuggestions** to the property "Suggestions".
5. As you will see, it looks to work (1 tag is shown) except that the tag/suggestions have no display name. Add the extra s as mentioned above will show the tag display names.

ClearCollect(
    coll_TagSuggestions,
    {
        SuggestionDisplayName: "Power Apps"
    },
        {
        SuggestionDisplayName: "Power Automate"
    },
        {
        SuggestionDisplayName: "Power BI"
    }
);
ClearCollect(
     coll_Tags,
    {
        TagDisplayName: "Power Apps"
    }
)

**Expected behavior**
I expect tags to have a display name.

**Screenshots**
Wrong
![image](https://user-images.githubusercontent.com/35654198/191301475-987f42d9-a646-499c-8213-1204133e81fa.png)

Good
![image](https://user-images.githubusercontent.com/35654198/191301326-e0e5fb6a-4727-4a99-a306-df72f65022e0.png)

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
A fix is provided here too (see "Describe the bug"). The better fix is imo to update the code so no extra s is needed. A naming without the extra s seems to be more precise imo.

**Comment by formsandflows** [comment]
Solution version used: CreatorKitCore_1_0_20220831_1_managed

**Comment by scottdurow** [comment]
Thanks for this @formsandflows  - the dataset properties are all prefixed with the name of the property - so in this case 'Tags' and 'Suggestions'

@denisem-msft This needs an update to the docs.

**Comment by mikefactorial** [comment]
@formsandflows This has been fixed in the latest release.
