### ISSUE TITLE
CREATOR KIT REFERENCE APP Looks different then it was previewed 

### ISSUE THREAD

**Issue by sekharmalla** [microsoft/powercat-creator-kit#12]
Hi dear wonderful powercat team, this is my first ever experience in creating an issue, please excuse for any mistake,

so yesterday i have seen the announcement on twitter and today i have started following this [guide](https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/overview) to get started, and after successfully deploying the solution i have opened CREATOR KIT REFERENCE APP then i noticed something is not right, i just took the screenshot and opening this issue, i know it's pre-release and Creator-kit in preview so i thought i should let you know this issue, Thank you very much what you've been doing for every Power Platform user out there, kudos 👍🏼 

![image](https://user-images.githubusercontent.com/43902003/168742118-cd4092a3-de5a-4ff0-8f4a-6968f94724f4.png)

**Comment by tcvdw1605** [comment]
I'm having the same issue. Running it on my community plan environment and 'Allow publishing of canvas apps with code components' is enabled in my environment settings.

**Comment by sekharmalla** [comment]
[Update] I have used Default Environment(Europe) and followed the same steps to import the solution. It worked! Maybe give it a try.

**Comment by sekharmalla** [comment]
I believe it is because of this prerequisite: _A Premium Power Apps license is required to develop and use apps with custom components._

**Comment by tcvdw1605** [comment]
Ok, I got this solved. You need to have 'Allow publishing of canvas apps with code components' enabled before importing the Creator Kit managed solution.

So, if you're having the same issue. First, remove the Creator Kit solution from your environment (and all its dependencies). After this, enable the PCF option in your environment's settings and then import the Creator Kit solution again. Don't forget to publish all customizations.

**Comment by slaouist** [comment]
In the docs: https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/setup, we mention in the the pre-requisite section to enable the code components prior to the installation steps...  .Maybe we should make the docs a bit more explicit on this.  Thank you !
