### ISSUE TITLE
[BUG]: Different theme variable must be used for code/canvas components

### ISSUE THREAD

**Issue by formsandflows** [microsoft/powercat-creator-kit#121]
**Describe the bug**
For a canvas component, the variable "AppTheme" (as in line with documentation) must be used and for a code component the variable "AppThemeJson" must be used.

It works if you know this but using only one for both type of components is more user friendly imo.

**To Reproduce**
1. Create a new canvas app.
2. Add the code as mentioned in the following page to add the variables "AppTheme" and "AppThemeJson": https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/theme
3. Add a canvas component and a code component from the Creator Kit.
4. Canvas component:
    Configure the variable "AppThemeJson" for the theme. An error is shown. When using the variable "AppTheme", no error is shown.
5. Code component:
    Configure the variable "AppTheme" for the theme. An error is shown. When using the variable "AppThemeJson", no error is shown.

**Expected behavior**
Only one of the variables is used independent of the type of component.

I personally prefer "AppTheme" because it makes the reuse of this variable easier for makers who will also use their own canvas components using a theme property.

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by formsandflows** [comment]
Solution version used: CreatorKitCore_1_0_20220831_1_managed

**Comment by denisem-msft** [comment]
@formsandflows thanks for your great feedback.

This is a known limitation as canvas and code component frameworks slightly differ in ability to pass in values. We have tried to make the required steps to theme both types clearly in our documentation and make the conversion to JSON as easy as possible, but unfortunately there is still that extra step needed.

We are looking into different ways to make theming as easy as possible as we go forward and will strive to make a unified theming option.
