### ISSUE TITLE
[BUG]: SearchBox control has a fixed blue border color for hover/pressed events

### ISSUE THREAD

**Issue by formsandflows** [microsoft/powercat-creator-kit#122]
**Describe the bug**
The component "SearchBox" has a blue border color for hover and pressed events even if this color is not configured in the theme.

**To Reproduce**
1. Create a new canvas app.
2. Add a theme variable as mentioned on the page: https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/theme
3. Add the component "SearchBox".
4. Configure the theme of the "SearchBox" component.
5. Hover over and press the "SearchBox" component.

**Expected behavior**
I expect that the color "themePrimary" or a good neutral color is used for the border color for hover/pressed events.

**Screenshots**
![image](https://user-images.githubusercontent.com/35654198/192093165-e340e969-d90d-4030-9952-c1faa9f8421b.png)

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
Solution version used: CreatorKitCore_1_0_20220831_1_managed

**Comment by formsandflows** [comment]
A custom theme must be used to see this bug. I used:
```
Set(
    glb_Theme,
    {
        palette: {
            themePrimary: "#00ad56",
            themeLighterAlt: "#f2fcf7",
            themeLighter: "#cbf2df",
            themeLight: "#a1e7c4",
            themeTertiary: "#52ce90",
            themeSecondary: "#16b767",
            themeDarkAlt: "#009c4e",
            themeDark: "#008442",
            themeDarker: "#006131",
            neutralLighterAlt: "#faf9f8",
            neutralLighter: "#f3f2f1",
            neutralLight: "#edebe9",
            neutralQuaternaryAlt: "#e1dfdd",
            neutralQuaternary: "#d0d0d0",
            neutralTertiaryAlt: "#c8c6c4",
            neutralTertiary: "#a19f9d",
            neutralSecondary: "#605e5c",
            neutralSecondaryAlt: "#8a8886",
            neutralPrimaryAlt: "#3b3a39",
            neutralPrimary: "#323130",
            neutralDark: "#201f1e",
            black: "#000000",
            white: "#ffffff"
        }
    }
);
```

**Comment by denisem-msft** [comment]
This has been fixed and will be available in the October release.
