### ISSUE TITLE
[Feature] SearchBox comotrl > Be able to set the border width to 0 

### ISSUE THREAD

**Issue by formsandflows** [microsoft/powercat-creator-kit#123]
**Is this request for a new component, or additional functionality for an existing component? **
Additional functionality.

**Have you validated that your desired feature or component is not already in the [backlog](https://github.com/microsoft/powercat-creator-kit/issues?q=is%3Aopen+is%3Aissue+label%3Abacklog)?**
Yes

(This question is useful for reporting a bug too).

**Describe the component and functionality you would like to see in the starter kit**
Being able to set the border width to 0 so that placing this control "in" an elevation looks much nicer.

Not so nice:
![image](https://user-images.githubusercontent.com/35654198/192093603-02ee465c-49b6-479b-a5b5-b32d3454f4df.png)

Nice:
![image](https://user-images.githubusercontent.com/35654198/192093683-1f52e956-cbc6-4b03-bd7b-dda7b2c15f07.png)

**Describe alternatives you've considered**
Because this control is a canvas control, you can edit it yourself without having to be a full-code developer. Creating my own SearchBox control is an alternative.

**Additional context**
Solution version used: CreatorKitCore_1_0_20220831_1_managed

**Comment by denisem-msft** [comment]
Would the underlined version of the SearchBox be sufficient, or are you really looking for no border? I am asking because Fluent UI does not offer a search box without either a border or underlined, and we are trying to align with Fluent as much as possible.

**Comment by denisem-msft** [comment]
@formsandflows please check out the new code component version of [SearchBox](https://github.com/microsoft/powercat-code-components/tree/main/SearchBox) and see if the underlined version works better for you.

**Comment by denisem-msft** [comment]
@formsandflows Closing this for now, please reopen if this doesn't meet your requirements.
