### ISSUE TITLE
[BUG]: Dialog control ignores the theme for button hover/pressed events

### ISSUE THREAD

**Issue by formsandflows** [microsoft/powercat-creator-kit#124]
**Describe the bug**
The component "Dialog" has a blue color for hover and pressed events even if this color is not configured in the theme.

**To Reproduce**
1. Create a new canvas app.
2. Add a theme variable as mentioned on the page: https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/theme
Add the component "Dialog".
3. Configure the theme of the "Dialog" component.
4. Hover over and press the "Dialog" component.

**Expected behavior**
I expect the button to behave as a Fluent UI button.

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
Solution version used: CreatorKitCore_1_0_20220831_1_managed

A custom theme must be used to see this bug. I used:
```
Set(
    glb_Theme,
    {
        palette: {
            themePrimary: "#00ad56",
            themeLighterAlt: "#f2fcf7",
            themeLighter: "#cbf2df",
            themeLight: "#a1e7c4",
            themeTertiary: "#52ce90",
            themeSecondary: "#16b767",
            themeDarkAlt: "#009c4e",
            themeDark: "#008442",
            themeDarker: "#006131",
            neutralLighterAlt: "#faf9f8",
            neutralLighter: "#f3f2f1",
            neutralLight: "#edebe9",
            neutralQuaternaryAlt: "#e1dfdd",
            neutralQuaternary: "#d0d0d0",
            neutralTertiaryAlt: "#c8c6c4",
            neutralTertiary: "#a19f9d",
            neutralSecondary: "#605e5c",
            neutralSecondaryAlt: "#8a8886",
            neutralPrimaryAlt: "#3b3a39",
            neutralPrimary: "#323130",
            neutralDark: "#201f1e",
            black: "#000000",
            white: "#ffffff"
        }
    }
);
```

**Comment by denisem-msft** [comment]
This has been fixed and will be available in the next release
