### ISSUE TITLE
[BUG]: Typo in Dialog component

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/powercat-creator-kit#127]
In the Dialog component, the Overlay colour in the properties is called Ovelay Color:
![image](https://user-images.githubusercontent.com/55705669/192301264-101eb84c-6671-4da1-a185-3ae409987e20.png)

**Comment by slaouist** [comment]
@manuelap-msft This is now fixed and will ship in the October release. Thanks for reporting !
