### ISSUE TITLE
[BUG]: ContextMenu intermittently fails to render in flexible gallery

### ISSUE THREAD

**Issue by denise-msft** [microsoft/powercat-creator-kit#129]
**Describe the bug**
Some components like ContextMenu are intermittently failing to render in a gallery template if there are enough items in the gallery that allows the template row to scroll out of view. Shown below, with a ContextMenu in a flexible height gallery, the component does not display correctly based on the Items collection passed in to define the visual appearance. When this happens, the component is not usable. 

**To Reproduce**
1. Create an AFS (in an environment with creatorkit installed)
1. Import the ContextMenu
1. Create a gallery that has 30 items (e.g., you can render with the table function: Table( {},{},{},{},{}) )
1. Insert a ContextMenu into the gallery template
1. Play the app and scroll up and down until the issue reproduces (ContextMenu does not render the input table items and is not usable)
 
**Expected behavior**
ContextMenu is rendered correctly in each row

**Screenshots**
![image](https://user-images.githubusercontent.com/43950360/192945969-dab20770-4ea5-4a78-b5b5-c951a05006cf.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: Windows 11
 - Browser: [Edge Version 105.0.1343.53]

**Comment by mikefactorial** [comment]
@denise-msft This has been fixed in the latest release.
