### ISSUE TITLE
[Creator Starter Kit] Documentation: the 'discussions' link on Github home page leads to a 404 page

### ISSUE THREAD

**Issue by e-gallis** [microsoft/powercat-creator-kit#14]
On the Github home page for the [PowerCAT Creator Kit](https://github.com/microsoft/powercat-creator-kit), the '_discussions_' link in paragraph '_Asking and Answering Questions_' leads to a 404 page.

**Comment by slaouist** [comment]
Thanks for reporting this. I removed that link as we are going to use Issue to better track and respond to requests/questions.
