### ISSUE TITLE
[Feature]: PeoplePicker

### ISSUE THREAD

**Issue by denisem-msft** [microsoft/powercat-creator-kit#150]
**How to promote this component**
Thumbs up 👍 this post to promote this backlog item. Please share usage scenarios in the comments.

**Component description**
The people picker (`PeoplePicker`) is used to select one or more entities, such as people or groups, from a list. It makes composing an email to someone, or adding them to a group, easy if you don’t know their full name or email address.

![image](https://user-images.githubusercontent.com/43950360/195757804-1f0769cf-7400-4f55-840e-a00e2ff53793.png)

[Fluent UI documentation](https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker)

**Comment by sperry1625** [comment]
I have an app that is used to control access to other power apps.  Having this would improve the apps usage when selecting users and or groups. Needs to have a filter property if we need to limit who can be chosen, Maybe by AAD Property or only users within a specific group can be selected, etc.

**Comment by denisem-msft** [comment]
This is available now in the October release.

@sperry1625 you have full control over which data set is displayed in the suggestions, see the [component documentation](https://github.com/microsoft/powercat-code-components/tree/main/PeoplePicker) for more details.
