### ISSUE TITLE
[Creator Starter Kit] BUG:

### ISSUE THREAD

**Issue by PowerPlatformPhillips** [microsoft/powercat-creator-kit#16]
**Describe the bug**

The apps are mostly blank. So the theme app is 100% blank apart from the header.

The reference app has a bit of text about the auto width label, but the menu on the left is blank and the use and don't use are way down the screen after scrolling and you cannot fully see the text even then.

Not sure if using a Power Apps Developer Environment is the issue?

**To Reproduce**

Version: CreatorKitCore_1.0.20220514.1_managed

1. Imported solution into a Power Apps Developer Environment.

2. Enabled Custom Components via the Power Platform Admin Centre > Selected correct environment > Settings > Features > Toggled on

3. Launch the Reference App and Theme Creator

**Expected behavior**
Be able to see the reference app and theme creator apps in all there glory.

**Screenshots**
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/105748220/168895716-cd02eb15-6168-422e-86af-cd1d4b1e4207.png">
<img width="1917" alt="image" src="https://user-images.githubusercontent.com/105748220/168895811-cbbfe7a9-c9aa-444f-8395-e39d7acf8691.png">
<img width="1914" alt="image" src="https://user-images.githubusercontent.com/105748220/168895866-f05fc60b-4c91-4cc3-aa00-81d446affa20.png">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge

**Comment by slaouist** [comment]
Please enable code components in your environment. See pre-requisites requirement in the install instructions: https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/setup

**Comment by slaouist** [comment]
see this issue for additional details :https://github.com/microsoft/powercat-creator-kit/issues/12 

you will have to delete solution, enable code component and re-import the creator kit solution

**Comment by PowerPlatformPhillips** [comment]
Thanks,  I thought I had enabled custom components prior to import but perhaps not as it is the only thing that makes sense to cause this type of issue I suppose. 

Will check it again and report back if any further issues.
