### ISSUE TITLE
[BUG]: Cannot import Creator Kit

### ISSUE THREAD

**Issue by nbetters** [microsoft/powercat-creator-kit#167]
When trying to import the creator kit solution this error is populated

"The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported."

Installing from app source does seem to work, but I could not tell if there is a version difference between app source and git.

**Comment by sperry1625** [comment]
Unzip the downloaded zip.

Regards,

Steven Perry
***@***.***

**Comment by nbetters** [comment]
It fails to unzip
***@***.***

**Comment by sperry1625** [comment]
Then you may have gotten a bad download.  Try downloading again.

Regards,

Steven Perry
***@***.***

**Comment by nbetters** [comment]
Same issue, trying to unzip the file throws an error that the json file name is too long

**Comment by sperry1625** [comment]
Place the zip in a root folder or shorter path before unzipping. Full
filenames cannot be longer than 255 characters.


Regards,

Steven Perry
***@***.***

**Comment by nbetters** [comment]
ok, but now that it is unzipped how do you import it into the powerapps solution import? this requires the package to be zipped, if I rezip only the automationCOEmain for example it fails with the same error as the beginning.

**Comment by sperry1625** [comment]
Ok. The last time I downloaded the Creator Kit there were multiple ZIP
files in one. I just unzipped those and imported the individual ZIP files.
Not sure what you downloaded or what was in the ZIP you have.
It should be working.

Regards,

Steven Perry
***@***.***

**Comment by nbetters** [comment]
Humm.. I downloaded the set from git.

I guess, as long as appsource is up to date I can install it using the d365 app source just fine, I just wanted the most current update.

**Comment by denisem-msft** [comment]
You need to download the assets from the latest release page: https://github.com/microsoft/powercat-creator-kit/releases/latest

For example, download the file that says "CreatorKitCore_1.0.20221004.2_managed.zip" to download the core solution.

Import those directly (do not unzip) and it should work.

(Thank you @sperry1625 for helping troubleshoot)

**Comment by denisem-msft** [comment]
@nbetters can you please try downloading from the release page and confirm if that import worked for you?
