### ISSUE TITLE
[BUG]: ContentY in Dialog Control does not take the subtitle into account

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/powercat-creator-kit#172]
**Describe the bug**
This is pretty minor, but I've added the dialog control with a title and subtitle and want to add a gallery in the content area of the dialog. When I use the ContentY value of the dialog control it adds the gallery under the Title and doesn't take the height of the subtitle into consideration: 

![image](https://user-images.githubusercontent.com/55705669/200398709-8fd5e7b0-20eb-4f85-9d07-b9b7a07262b5.png)

ContentX also adds the content in a way that's not aligned with the title and subtitle (I think missing about 10px) 

**Expected behavior**
ContentY takes Subtitle into consideration and ContentX lines up the content with the title and subtitle. 

**Screenshots**
If using ContentX and ContentY without adding some extra padding
![image](https://user-images.githubusercontent.com/55705669/200399005-7db589c7-8d8d-473a-9bd1-41640a41b89d.png)

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release.
