### ISSUE TITLE
[Creator Starter Kit] BUG: Fluent Theme Designer OnSelect property for Upload element launches URL in same tab

### ISSUE THREAD

**Issue by cclarktax** [microsoft/powercat-creator-kit#18]
**Describe the bug**
When pressed, the Upload button launches a [URL](https://developer.microsoft.com/en-us/fluentui) when pressed that opens in the same browser tab as the app.

**To Reproduce**

1. Open Fluent Theme Designer managed app in Play mode
2. Left mouse click on Upload button

**Expected behavior**

Upon pressing the button, nothing should occur aside from a state reset from pressed to not pressed.

**Screenshots**

Hovering over the button reveals the URL:
![image](https://user-images.githubusercontent.com/48168322/169342444-2e1a93b0-0cdf-4ae2-ba85-7d2c6b0be935.png)

Result from pressing button:
![image](https://user-images.githubusercontent.com/48168322/169342721-560b8130-3c59-4203-9b58-d59ed6973dbf.png)
**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome and edge
 - Version N/A

**Additional context**
To resolve simply delete info in the OnSelect property of the Upload element.

**Comment by slaouist** [comment]
Thanks for reporting this. This is external to the Fluent UI underlying theming control. We will work with them to try to fix this but likely low priority. The controls in the Fluent Designer are for displaying the theme colors updates.
