### ISSUE TITLE
[BUG]: Child Canvas app is not found in root app manifest

### ISSUE THREAD

**Issue by Marvinnnne** [microsoft/powercat-creator-kit#188]
I have installed the 3 managed solutions manually.
![image](https://user-images.githubusercontent.com/9744563/202134407-78398cf8-fda8-471f-9b6f-7ae4f95975ed.png)

I enable code components on my environment.

And when i open Creator Kit Reference App model driven app, i'm facing this issue :
Child Canvas app is not found in root app manifest

I have no issue when i open Creator Kit Reference App canvas app.

Thanks for your help

**Comment by Marvinnnne** [comment]
Hello,
No Sorry.
I face the same issues with my other custom page. I saw another blog to create a empty custom page, remove the one which causing issue, publish and re add it in order to regenerate root app manifest. It works for my other custom page. I didn't retry for yours custom page. 
Maybe it will help you.

**Comment by denisem-msft** [comment]
Closing this as there haven't been other reports of this happening. Please reopen if this issue happens again.
