### ISSUE TITLE
[Creator Starter Kit] BUG: Unable to view content on bottom of pages

### ISSUE THREAD

**Issue by DaveStabilify** [microsoft/powercat-creator-kit#19]
**Describe the bug**
Vertical Scroll is not working on several pages of the Reference App and Theme Designer.

**To Reproduce**
FOR REFERENCE APP
1. Go to 'Surfaces | Panel' or 'Surfaces | Dialog' or 'Progress | Spinner' or 'Progress | Progress Indicator'
2. Try to scroll to see content on bottom of page.

FOR THEME DESIGNER
1. Try to scroll to see content on bottom of page. (had to set **Vertical Overflow** to **Scroll**)

**Expected behavior**
View all content on the page.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version 101.0.4951.67

**Additional context**

**Comment by slaouist** [comment]
Thank you for reporting this. We will fix this and release asap.
