### ISSUE TITLE
[BUG]: ExpandMenu adds 1MB+ to size of each screen

### ISSUE THREAD

**Issue by ericsnowgh** [microsoft/powercat-creator-kit#194]
Hi folks,

I've noticed the ExpandMenu component adds ~1 MB per .yaml file to the size of my Canvas Apps. When the .msapp file is unpacked, it shows that the "GetMenuIconPath" property of the ExpandMenu component contains a hard-coded table with reference to thousands of FluentUI Icons embedded (11,300 lines total added to every yaml file that contains the ExpandMenu component). Wasn't sure of whether this is expected behavior or not, but it seems unusual compared to other Power Apps components I've seen or used 

Sample screenshot showing the first few lines of an unpacked yaml file: 
![image](https://user-images.githubusercontent.com/103667812/203155422-81d61bd5-e0ec-45dd-b966-0d37f4ff2cf3.png)

**Comment by slaouist** [comment]
@ericsnowgh. Thank you for reporting this. We will definetly fix this when embeeding PCF components within canvas components becomes supported. In that case, we will be able to use the Fluent Icon control.

**Comment by mikefactorial** [comment]
@ericsnowgh This has been fixed in the latest release.
