### ISSUE TITLE
[BUG]: BUG/Feature Request: Details List Related Table (1:N) Column

### ISSUE THREAD

**Issue by zakirakhan** [microsoft/powercat-creator-kit#198]
Hello,

I am showing Contacts in the List. Is there any way to show related table column in same list? 

 There is another table Table 2 related to Contacts.  Contact  has one to many relationship with Table 2.

Thanks

**Comment by denisem-msft** [comment]
Please see the response from Scott in #197 regarding use of AddColumns, and making sure the table is in the app.
