### ISSUE TITLE
[BUG]: Dialog Box Pressed/HoverFillColor

### ISSUE THREAD

**Issue by medoomi** [microsoft/powercat-creator-kit#199]
**Describe the bug**
The HoverFillColor and PressedFillColor of the (primary) buttons in the dialog box have not been set to AppTheme colors (they default to blue)

**Expected behavior**
On Hover & Pressed actions, I believe the color of a primary button should reflect a neutral color, like in the buttons in the "canvas template" app (or whatever is appropriate for a fluent UI color scheme)

Thanks for all the work on the Creator Kit!

**Comment by denisem-msft** [comment]
Mapped the following dialog properties for each button type to the associated theme palette values and will be available in the next release. Please let us know if more mapping is needed.

| Button type | Dialog property | Semantic slot | Palette value |
|-|-|-|-|
| Primary | Color | primaryButtonText | white |
| Primary | HoverFillColor | primaryButtonBackgroundHovered | themeDarkAlt |
| Primary | PressedFillColor | buttonBackgroundPressed | themeDark |
| Primary | DisabledFillColor | primaryButtonBackgroundDisabled | neutralLight |
| Default | Color | bodyTextChecked | black |
| Default | Fill | buttonBackground | white |
| Default | HoverFillColor | buttonBackgroundHovered| neutralQuaternary|
| Default | PressedFillColor  | buttonBackgroundPressed | neutralTertiary |
| Default | DisabledFillColor | primaryButtonBackgroundDisabled | neutralLight |
| Default | BorderColor | buttonBorder | neutralSecondaryAlt |
| Default | DisabledBorderColor | buttonBorderDisabled | neutralLighter |

**Comment by CrmDev23** [comment]
Hi @denisem-msft 
Could you please provide color mappings for the checkbox control?

**Comment by denisem-msft** [comment]
@CrmDev23 please go to the Theme slots > Semantic slots tab and view the mapping for slots related to "input" (e.g., _inputBackgroundChecked_ and _inputBackground_ would be the checkbox background fill): https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/theming-designer/

**Comment by mikefactorial** [comment]
@medoomi This has been fixed in the latest release.
