### ISSUE TITLE
[Creator Starter Kit] BUG: Bunch of Components do now show up.

### ISSUE THREAD

**Issue by ramonck** [microsoft/powercat-creator-kit#20]
After importing the solution and creating an unmanaged solution, I imported the Canvas Template and I do not see a bunch of components.

The left controls on the right is ok, everything on the right-side no.

Instructions: https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/creator-kit-explained

Downloaded from: https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/overview

Screenshot with the issue.

![image](https://user-images.githubusercontent.com/5229948/169537175-30b769bb-7deb-4640-a8db-e406e4b11589.png)

**Comment by slaouist** [comment]
@ramonck, Please enable Code Components in your environement. See Prerequesites in the docs: https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/setup 
To fix this, you will need to remove the solution, enable the code components in your environment and then re-import
