### ISSUE TITLE
[BUG]: Date Picker color styling

### ISSUE THREAD

**Issue by medoomi** [microsoft/powercat-creator-kit#204]
**Describe the bug**
Within the Date Picker (in the "Canvas Template")...
The highlighted color circle covering today's date defaults to blue, rather than the AppTheme colors
Also the Focused Border Color defaults to blue, instead of AppTheme colors

**Comment by denisem-msft** [comment]
@medoomi Are you talking about the DatePicker control and not the Calendar, right?

DatePicker is not part of the Creator Kit controls our team releases, it is a native control. Please treat it as any native control, where you can still reference the AppTheme as described in the documentation section [Referencing theme from native Power Apps components](https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/theme#referencing-theme-from-native-power-apps-components).
