### ISSUE TITLE
[BUG]: Controls disappeared in the new version 1.0.20221205.2

### ISSUE THREAD

**Issue by Juromudu** [microsoft/powercat-creator-kit#217]
I updated the Creator Kit version to CreatorKitCore_1.0.20221205.2_managed.zip
and Panel, Dialog and Expand Menu controls disappeared **when I try to add them to a new app.**

**If I already use** them in an app, **I can continue** using them without problems.

The three components are the **last** remaining **library components** in the kit, the others are code components.

Thanks!

**Comment by manuelap-msft** [comment]
Hello,

I had the same issue, and as a workaround what worked for me was

1. Navigating to make.powerapps.com > Apps
2. Select Component libraries
3. Edit Power CAT Component Library
4. Add an empty component (I just selected + New Component) 
5. re-publish the component library 
6. re-open the app/page I want to add the component too and now Panel etc appear again 

Hope this works for you too!

**Comment by Juromudu** [comment]
Hello 
  
it worked!!  
Thank you very much 
  
  
     

-----Mensaje original-----

De: Manuela ***@***.***>
Para: microsoft ***@***.***>
CC: Juromudu ***@***.***>; Author ***@***.***>
Fecha: martes, 13 de diciembre de 2022 6:21 -05
Asunto: Re: [microsoft/powercat-creator-kit] [BUG]: Controls disappeared in the new version 1.0.20221205.2 (Issue #217)

 

  Hello, I had the same issue, and as a workaround what worked for me was  
  1. Navigating to make.powerapps.com > Apps 
  2. Select Component libraries 
  3. Edit Power CAT Component Library 
  4. Add an empty component (I just selected + New Component) 
  5. re-publish the component library 
  6. re-open the app/page I want to add the component too and now Panel etc appear again  Hope this works for you too! —

**Comment by Niels-SL** [comment]
Cheers. This workaround also worked for me as I was getting a bunch of error messages for Panel and Dialog components.

![image](https://user-images.githubusercontent.com/46558783/223055020-65da494f-0d27-4e79-aa5a-ed8219f03957.png)

**Comment by kbelayba** [comment]
This is not working for me, as I can't edit the Power CAT Component Library
