### ISSUE TITLE
[Creator Starter Kit] Question on canvas app control naming convention

### ISSUE THREAD

**Issue by last72** [microsoft/powercat-creator-kit#24]
I can see different naming conventions within "Power CAT Component Library" - Components.

Is there a set guide for the new control naming? For example, "imgSearch", "SpinnerContent"

![image](https://user-images.githubusercontent.com/30095306/170516820-f751ec48-9c9e-4dd3-bb5d-dbb9f0547891.png)

**Comment by denisem-msft** [comment]
Hi @last72 - There is a coding standards whitepaper for Power Apps available here: https://powerapps.microsoft.com/en-us/blog/powerapps-canvas-app-coding-standards-and-guidelines/

In this case, the SpinnerContent is a container which groups components, and the imgSearch is a singular component. The fact that the container is a group of components differentiates them and the whitepaper describes individual components having the format of imgSearch.
