### ISSUE TITLE
[BUG]: Reference App - Fluent DetailsList Best Practices 

### ISSUE THREAD

**Issue by ArtKarp** [microsoft/powercat-creator-kit#251]
**Describe the bug**
In the Reference app for Fluent DetailsList, under Content,  it says "Use sentenance-style capitalization...".  In the example DetailList, it uses proper case (which is what I would do).   😁

![image](https://user-images.githubusercontent.com/25698082/210028880-7846c3a7-15df-4aa0-8f8e-7f51203a1d54.png)

**Comment by slaouist** [comment]
good catch :)  will look into it.

**Comment by denisem-msft** [comment]
This has been fixed in both the Canvas and Model Driven App solutions and will be available in the next release.

**Comment by mikefactorial** [comment]
@ArtKarp This has been fixed in the latest release.
