### ISSUE TITLE
[BUG]: Command Bar not loading buttons

### ISSUE THREAD

**Issue by elliotfraser** [microsoft/powercat-creator-kit#255]
**Describe the bug**
Occasionally I will be loading my embedded canvas app and the command bar buttons will render the default buttons (? Item 1  ? Item 2 | ? Item 3) rather than the ones I have defined. This doesn't happen all the time but it's frequent enough that I have to train users to reload the page if it happens which isn't ideal.

**To Reproduce**
I can't reproduce this consistently however it seems to happen frequently the first time I load the app from a new browser. On reload of the page it always then performs as expected.

**Expected behavior**
When loading the app with a command bar, the custom buttons that I have defined should appear rather than the default ones.

**Screenshots**

Here is what the command bar looks like when rendering incorrectly even though I have correctly defined the buttons.
![image](https://user-images.githubusercontent.com/112189810/210380657-b858703d-a0ac-4ad1-9082-baf63dff7c3c.png)

After reloading the page the buttons always seem to work as expected:
![image](https://user-images.githubusercontent.com/112189810/210381139-3f703819-a7fb-44d7-b30f-acd688744da3.png)

**Additional context**
This is happening in an embedded canvas app (not custom page).

**Comment by denisem-msft** [comment]
@elliotfraser can you please share a session ID of a session when the incorrect command bar is loading? How are you rendering the Items input, directly or via a collection? If you can share more details on steps to reproduce with data and browsers this is happening on more frequently so I can reproduce it, or even an export of the app with the repro, that would be very helpful.

**Comment by denisem-msft** [comment]
@elliotfraser are you still seeing this issue? If you can't share the session ID, can you please share the collection you're using to render the commandBar?

**Comment by elliotfraser** [comment]
Hi @denisem-msft , seems like this issue has resolved it's self as I haven't seen it occur in the last few weeks. Must have been a issue with my browser. Thanks for your response, I'll close this now
