### ISSUE TITLE
[BUG]: Creator Kit Reference App is broken

### ISSUE THREAD

**Issue by arpost1** [microsoft/powercat-creator-kit#257]
The Creator Kit Reference Canvas App has been loading strangely for a while now and is unusable. I downloaded the latest release ([November](https://github.com/microsoft/powercat-creator-kit/releases/tag/CreatorKit-November2022)), but the issue persists. When I refresh, the Best Practices/Don't galleries sometimes load at the top but often require a lot of scrolling to get to them. Guessing this is a responsive layout issue of some kind.

![image](https://user-images.githubusercontent.com/26190797/210832689-a70dd31e-32f6-489b-8fd9-edb0011032e4.png)

**Comment by denisem-msft** [comment]
@arpost1 did you enable the code components for canvas environment setting feature described in the documentation?: https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/setup#prerequisites

**Comment by arpost1** [comment]
I did indeed. I’m using code components in canvas apps elsewhere.On Jan 5, 2023, at 7:40 PM, Denise Moran ***@***.***> wrote:﻿
@arpost1 did you enable the code components for canvas environment setting feature described in the documentation?: https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/setup#prerequisites
