### ISSUE TITLE
[Feature]: Panel Component Buttons need to have visible / enabled features

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/powercat-creator-kit#268]
**Is this request for a new component, or additional functionality for an existing component? **
Additional functionality for an existing component

**Have you validated that your desired feature or component is not already in the [backlog](https://github.com/microsoft/powercat-creator-kit/issues?q=is%3Aopen+is%3Aissue+label%3Abacklog)?**
Backlog by this link appears empty, let me know if I'm missing something.

**Describe the component and functionality you would like to see in the starter kit**
Panel Component Button Properties: https://learn.microsoft.com/power-platform/guidance/creator-kit/panel#buttons-properties

Currently can only set label and Button type. 
In order for this component to really be reusable for a large and varried list of objects I need to be able to show or hide buttons based on state. 

Current example is the screen in the CoE to configure env vars. When there is no value, as shown here, then Revert should be hidden as there is nothing to revert to

![image](https://user-images.githubusercontent.com/89584709/212499687-33f21f2b-78e7-4547-ab57-28494605dbfe.png)

**Describe alternatives you've considered**
What I do now is throw an alert if they hit it.

**Comment by slaouist** [comment]
@Jenefer-Monroe. Removing the content of the property "Buttons" should hide the list. Works on Dialog and should work similarly on panel.

**Comment by slaouist** [comment]
new Buttons schema:
Table({Label: "Cancel", ButtonType:'Microsoft.CoreControls.Button.ButtonType'.Standard , Visible:true, Enabled:false} ,{Label: "Ok", ButtonType:'Microsoft.CoreControls.Button.ButtonType'.Primary, Visible:true, Enabled:false})

**Comment by slaouist** [comment]
fixed this for next release as well: "@Jenefer-Monroe. Removing the content of the property "Buttons" should hide the list. Works on Dialog and should work similarly on panel."

**Comment by Jenefer-Monroe** [comment]
> new Buttons schema: Table({Label: "Cancel", ButtonType:'Microsoft.CoreControls.Button.ButtonType'.Standard , Visible:true, Enabled:false} ,{Label: "Ok", ButtonType:'Microsoft.CoreControls.Button.ButtonType'.Primary, Visible:true, Enabled:false})

Thank you so much! This is exactly what I wanted!!!

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release.

**Comment by dancohenenterprise** [comment]
Updating to the latest Panel / Dialog components now require the Visible and Enabled properties to function properly.  The previous schema did not offer/require these properties.  This was unexpected, as after upgrading the components, no errors were apparent, but the buttons did not show.  

Please update the main documentation: https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/panel
