### ISSUE TITLE
[Creator Starter Kit] BUG: columns not appearing in Details List

### ISSUE THREAD

**Issue by bennyboy23** [microsoft/powercat-creator-kit#283]
When using the details list in tandem with a dataverse table, which has an additional column added from a different table, the new column that has been added, is not appearing when specified in the column items array.

**To Reproduce**
1. add a custom column within a custom page to a dataverse table
2. add the column to the fields
3. add the column to the column items
4. witness the lack of column

**Expected behavior**
The new column to be displayed

**Screenshots**
<img width="990" alt="Screenshot 2023-02-15 at 20 06 25" src="https://user-images.githubusercontent.com/6200604/219141292-6f41db2d-7dc4-4273-a8ab-ea0a2d9ef4ec.png">
<img width="1016" alt="Screenshot 2023-02-15 at 20 06 53" src="https://user-images.githubusercontent.com/6200604/219141351-3c0422c8-f4ca-4587-819b-84ba6742b85f.png">
<img width="1046" alt="Screenshot 2023-02-15 at 20 07 10" src="https://user-images.githubusercontent.com/6200604/219141380-67aaf500-10fd-4d38-9cbb-695f09105587.png">

**Additional context**
I am using a lookup to find the column data in a different table in dataverse.

**Comment by bennyboy23** [comment]
Hi,
Is there any sort of timeframe for when this might be looked at?

Thanks,

**Comment by yaseralhosani** [comment]
Hi, 

I haven't thought there is formula can do like Filter() As Record. 

I did similar to your way, but mine is working fine AddColumns(Filter(),"lookupname",LookUp()), the relationship is one-to-many.

I might help you if you could provide me an example, at least some samples for those tables. I will do my best

**Comment by bennyboy23** [comment]
Oooo, maybe it is my own hubris that has failed me here.
There is no relationship between the tables, they both have lookups to the product table and I want to find a product inventory where the product is equal to the related product on the work order product table. Let me try without the As step (I thought it would work as its within the addColumns function)

**Comment by bennyboy23** [comment]
> Oooo, maybe it is my own hubris that has failed me here. There is no relationship between the tables, they both have lookups to the product table and I want to find a product inventory where the product is equal to the related product on the work order product table. Let me try without the As step (I thought it would work as its within the addColumns function)
> 
> > Hi,
> > I haven't thought there is formula can do like Filter() As Record.
> > I did similar to your way, but mine is working fine AddColumns(Filter(),"lookupname",LookUp()), the relationship is one-to-many.
> > I might help you if you could provide me an example, at least some samples for those tables. I will do my best

My code is working as I got a response when using a monitor session... 
`{
  "status": 200,
  "duration": 62,
  "dataSource": "Product Inventory",
  "responseSize": 1034,
  "controlName": "dtlProductList",
  "propertyName": "Items",
  "nodeId": 18,
  "formulaData": {
    "script": "AddColumns(\n    Filter(\n        'Work Order Products',\n        'Work Order'.'WO Number' = RecordItem.'WO Number'\n    ) As WOProduct,\n    \"QuantityinStock\",\n    LookUp(\n        'Product Inventory',\n        Product.Product = WOProduct.Product.Product\n    ).'Quantity Available'\n)",
    "spanStart": 160,
    "spanEnd": 254
  },
  "data": {
    "context": {
      "entityName": "dtlProductList",
      "propertyName": "Items",
      "id": 1935,
      "nodeId": 18,
      "diagnosticContext": {
        "dataOperation": {
          "protocol": "cds",
          "operation": "getRows",
          "dataSource": "Product Inventory",
          "apiId": "CdsNative",
          "table": "msdyn_productinventories",
          "operationName": "CdsConnector.getRowsAsync"
        },
        "formula": "AddColumns(\n    Filter(\n        'Work Order Products',\n        'Work Order'.'WO Number' = RecordItem.'WO Number'\n    ) As WOProduct,\n    \"QuantityinStock\",\n    LookUp(\n        'Product Inventory',\n        Product.Product = WOProduct.Product.Product\n    ).'Quantity Available'\n)",
        "span": {
          "start": 160,
          "end": 254
        }
      }
    },
    "request": {
      "url": "https://guide-development.crm11.dynamics.com/api/data/v9.0/msdyn_productinventories?%24filter=msdyn_product%2Fproductid+eq+1fd55489-f429-ed11-9db2-002248414552&%24select=msdyn_productinventoryid%2Cmsdyn_qtyavailable%2Cmsdyn_product%2Cmsdyn_name%2Ccreatedon%2C_msdyn_product_value&%24top=1",
      "method": "GET",
      "headers": {
        "Accept": "application/json",
        "Prefer": "odata.continue-on-error",
        "x-ms-user-agent": "PowerApps/3.23021.21 (Web AuthoringTool; AppName=f9fe0508-3f2a-479e-b676-56efbdc9a401)",
        "x-ms-client-session-id": "b5103ba6-994c-4baa-b391-b98ab7cde6c4",
        "x-ms-client-request-id": "c887a04b-89bb-4adf-a2bf-33c4623d42b8",
        "Request-Id": "c887a04b-89bb-4adf-a2bf-33c4623d42b8",
        "Client-Session-Id": "b5103ba6-994c-4baa-b391-b98ab7cde6c4",
        "x-ms-app-id": "f9fe0508-3f2a-479e-b676-56efbdc9a401",
        "Accept-Language": "en-GB",
        "Cache-Control": "no-cache, no-store",
        "Content-Type": "multipart/mixed;boundary=batch_e0f164b5-8791-4153-a037-6390bce7de73"
      },
      "body": ""
    },
    "response": {
      "duration": 62,
      "size": 1034,
      "status": 200,
      "headers": {
        "Content-Type": "application/json; odata.metadata=minimal",
        "OData-Version": 4,
        "Preference-Applied": "odata.include-annotations=\"*\"",
        "Cache-Control": "no-cache",
        "content-encoding": "gzip",
        "Content-Length": 648,
        "expires": -1,
        "odata-version": 4,
        "req_id": "ad60d599-8b32-455e-b166-7c278268fe48"
      },
      "body": {
        "@odata.context": "https://guide-development.crm11.dynamics.com/api/data/v9.0/$metadata#msdyn_productinventories(msdyn_productinventoryid,msdyn_qtyavailable,msdyn_product,msdyn_name,createdon,_msdyn_product_value)",
        "@Microsoft.Dynamics.CRM.totalrecordcount": -1,
        "@Microsoft.Dynamics.CRM.totalrecordcountlimitexceeded": false,
        "@Microsoft.Dynamics.CRM.globalmetadataversion": 20962210,
        "value": [
          {
            "@odata.etag": "W/\"20962506\"",
            "msdyn_productinventoryid": "0d0858e9-32b1-ed11-83ff-00224841b8de",
            "msdyn_qtyavailable@OData.Community.Display.V1.FormattedValue": 5,
            "msdyn_qtyavailable": 5,
            "msdyn_name": null,
            "createdon@OData.Community.Display.V1.FormattedValue": "20/02/2023 15:26",
            "createdon": "2023-02-20T15:26:24Z",
            "_msdyn_product_value@OData.Community.Display.V1.FormattedValue": "120 Watt Amplifier 100v O/P",
            "_msdyn_product_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "msdyn_product",
            "_msdyn_product_value@Microsoft.Dynamics.CRM.lookuplogicalname": "product",
            "_msdyn_product_value": "1fd55489-f429-ed11-9db2-002248414552"
          }
        ]
      },
      "responseType": "json"
    },
    "startTime": 1049997,
    "name": "https://guide-development.crm11.dynamics.com/api/data/v9.0/$batch",
    "fetchStart": 1049997,
    "responseEnd": 1050054,
    "nextHopProtocol": ""
  }
}`

**Comment by yaseralhosani** [comment]
Hi, 

This is an example and working fine for me. It's fine you can also do without a relationship between tables as long as another table is a unique record.
https://user-images.githubusercontent.com/5079423/220147264-c1bd2764-2ea5-4df5-ab77-6097a312813b.mov

**OnSelect[Get Data]**
```
ClearCollect(
    'Work Order Products',
    Table(
        {
            id: 1,
            work_order_id: 1001,
            product_name: "Widget A",
            quantity: 10
        },
        {
            id: 2,
            work_order_id: 1002,
            product_name: "Widget B",
            quantity: 5
        },
        {
            id: 3,
            work_order_id: 1003,
            product_name: "Widget C",
            quantity: 20
        },
        {
            id: 4,
            work_order_id: 1004,
            product_name: "Widget D",
            quantity: 5
        }
    )
);
ClearCollect(
    'Product Inventory',
    Table(
        {
            id: 1,
            product_name: "Widget A",
            quantity: 100,
            location: "A1"
        },
        {
            id: 2,
            product_name: "Widget B",
            quantity: 50,
            location: "B3"
        },
        {
            id: 3,
            product_name: "Widget C",
            quantity: 75,
            location: "A2"
        },
        {
            id: 4,
            product_name: "Widget D",
            quantity: 150,
            location: "B1"
        }
    )
)
```
**OnSelect[Clear]**
```
Clear('Work Order Products');
Clear('Product Inventory')
```

**DetailsList.ColumnsItems**
```
Table(
    {
        ColName: "product_name",
        ColDisplayName: "Product Name",
        ColWidth: 300
    },
    {
        ColName: "quantity",
        ColDisplayName: "Quantity",
        ColWidth: 100
    },
    {
        ColName: "QuantityinStock",
        ColDisplayName: "Quantity in Stock",
        ColWidth: 100
    }
)
```

**DetailsList.Items**
```
AddColumns(
    'Work Order Products' As Record,
    "QuantityinStock",
    LookUp(
        'Product Inventory',
        ThisRecord.product_name = Record.product_name
    ).quantity
)
```

**Comment by bennyboy23** [comment]
You are correct in what you are saying and I really appreciate your efforts on finding a solution for this, however, the control is not rendering my new column.
My AddColumns is working as intended:
![Screenshot 2023-02-20 at 15 40 56](https://user-images.githubusercontent.com/6200604/220149528-da53df0b-2d3d-468c-97a2-b7285bb21643.png)

**Comment by bennyboy23** [comment]
As per usual it is user error! 
My column_items list was incorrect. I was using colName not ColName (capitalisation is key!)

**Comment by yaseralhosani** [comment]
How I did miss that lolz xD

**Comment by bennyboy23** [comment]
> How I did miss that lolz xD.
> 
> Ok so it solved

Yes it is solved, thank you so much for your time on this
