### ISSUE TITLE
[BUG]: Dialog component - mistake in Secondary Label (Size property)

### ISSUE THREAD

**Issue by PRusakPL** [microsoft/powercat-creator-kit#300]
**Describe the bug**
Inside Component Library for component Dialog there is a small mistake (a believe just a typo)
In control named **Label3_1** - **Size** property has wrong default value assigned to it.
It is: **Font.'Segoe UI'**
Should be: numeric value, e.g. **12**

**To Reproduce**
1. Open Component Library 
2. Find control named **Label3_1**
3. Locate Size property for this control

**Expected behavior**
Control should have numeric value assigned to Size property.

**Screenshots**
![image](https://user-images.githubusercontent.com/61137411/223691028-54e90606-90dd-4d0a-b65a-d60bd3a5a446.png)

**Additional context**
N/A

**Comment by mikefactorial** [comment]
@PRusakPL This has been fixed in the latest release.
