### ISSUE TITLE
[Creator Starter Kit] BUG:

### ISSUE THREAD

**Issue by C-A-BIRD** [microsoft/powercat-creator-kit#32]
Creator Kit downloaded & installed successfully from https://docs.microsoft.com/en-gb/power-platform/guidance/creator-kit/overview

I opened the creator Kit reference App expecting to view 
![CreatorReferenceApp](https://user-images.githubusercontent.com/9393667/171997139-81ba3f8c-f9f4-48c4-9e2b-7402141481cd.png)
As shown in April Dunnam's excellent YouTube demo https://www.youtube.com/watch?v=L599ttvkXwI&t=1s

Instead, I viewed 
![CreatorAppReference](https://user-images.githubusercontent.com/9393667/171997152-4b4dabb9-f6c9-4a19-9620-31b3c31271ff.png)
blank. 

I downloaded it again and installed it into a different Power App environment and got the same result. 

Is the issue with me or is there a bug? 

Thank you.

**Comment by slaouist** [comment]
Hello @C-A-BIRD, Please delete the solution, enable the code components in your environment and then re-import the solution. See docs installation prerequestites: 
<img width="726" alt="image" src="https://user-images.githubusercontent.com/8174072/172106844-83bead3d-46fa-409f-ba83-18e155d1a138.png">

**Comment by slaouist** [comment]
duplicate bug #16
