### ISSUE TITLE
[BUG]: CRITICAL : Dataverse Legacy dependency for the Code Components of Creator Kit

### ISSUE THREAD

**Issue by dineshary** [microsoft/powercat-creator-kit#323]
**Describe the bug**
When i add creator kit components to the canvas app (Icon, DetailsList), there is a dependency on Dataverse Legacy is also created. But i am not using anything related to Dataverse or Dataverse legacy. This issue occurs with the Code components like icon, details list etc

**_This looks very critical as the Dataverse Legacy connector is getting depreciated very soon._**

**To Reproduce**
1. Create a canvas app
2. Add DetailsList, Icon creator kit components to the app
3. Save and try Sharing the app. Data permissions section in the Share Dialog shows Dataverse now even though there are no Dataverse involved in the app
4. Try moving the solution to another environment where dataverse legacy connector is blocked, app will not open due to DLP

**Expected behavior**
Dataverse legacy must not be a dependency for the app

**Screenshots**
App: (If the Dataverse legacy is not blocked as per the DLP policy)
![image](https://user-images.githubusercontent.com/19535010/235203205-fde8e526-d463-4aba-b8a4-1ca3f67d14e7.png)

**App: (If the Dataverse legacy is Blocked as per the DLP policy)**
I tried adding the Details list component with datasource from Office365 users. Also, there is only one Connector used in the canvas app which is Office365Users

![image](https://user-images.githubusercontent.com/19535010/235209037-6a483515-d8b4-4508-9196-5fc117b9c8b0.png)

**Additional context**

AB#969

**Comment by schngupta** [comment]
This bug is a significant obstacle for my PowerApp because several external users depend on the app to submit critical business information. Unfortunately, the app's integration with Dataverse requires a premium license, which I do not believe external users can obtain.

**Comment by dineshary** [comment]
@denise-msft When i click Show tables, it doesnt show any tables. The screenshots provided are from the app built from scratch with the steps described.

We have multiple canvas apps in our organization with creator kit and sharepoint as data source, they all have the same issue even though dataverse or dataverse legacy are not used in the apps

**Comment by RiccoHippDev** [comment]
Hello people
I'm here briefly because I can also.say something on the subject.

I have spent the last two days with Microsoft support because of exactly the same issue. 

In my case, the code component "Command Bar" was to blame for the generation of a dataverse connection.


The reason is, according to Microsoft the Following Licence(change):

> Code Components that connect to external services or data directly via the user's browser client and not throught connectors are conisdered as premium. When these components are used in an app, the app becomes premium, and the end-users are required to have PowerApps Licences.

**Comment by dineshary** [comment]
@RiccoHippDev Thanks a lot for sharing!! How did you manage to solve this reference to Dataverse Legacy?

In my case, i am not using Dataverse in the app and sharepoint is the only datasource connected to it.

**Comment by RiccoHippDev** [comment]
I'm sorry to dissapoint you but the only solution is to remove the code component from the App. 

After that you stil have the Dataverse Conenction in the Sharing Menu but you can share it without assigning a security roles.
Users have then access to the app without a PowerApps Licence

**Comment by dineshary** [comment]
@RiccoHippDev Thanks for the reply!

I am fine with the issue since it is not impacting anything at the moment. BUT it still has the dependency on Dataverse Legacy connector in the DLP policy. If i remove that, app does not work. 

Microsoft is slowly depreciating the Dataverse legacy connector in different parts of power platform, i am worried about that. One day, many of my apps will not work suddenly

**Comment by dineshary** [comment]
When i move the solution to a different environment and open the app. It shows the error that the App is not compliant to the DLP policy.

**_Business connector: shared_office365users cannot be used with non-business connector: /providers/Microsoft.PowerApps/apis/shared_commondataservice._**

The Target environment has Dataverse connector enabled as a Business Connector but not the Dataverse legacy connector.

If i enable Dataverse legacy connector as a business connector in the target environment, then everything works well

**Comment by aleeland** [comment]
Hello everyone, it looks like this is still an open issue. I am a member of the MSFT Power Platform DLP team and we are trying to block the legacy Dataverse connector also within DLP policies, but this would break users' apps that have the Creator Kit in their environment (mine included). Is there a timeline for resolution for this?

**Comment by rarattay** [comment]
Hello, The team has deployed a fix to address this issue. Please let us know if you see this issue still occurring for you.
