### ISSUE TITLE
[Creator Starter Kit] BUG: Unable to import unmanaged solution

### ISSUE THREAD

**Issue by last72** [microsoft/powercat-creator-kit#33]
**Describe the bug**

**To Reproduce**
1. Download unmanaged solution from releases
2. Import using Power Apps

**Expected behavior**
Solution imported as unmanaged

**Screenshots**
![image](https://user-images.githubusercontent.com/30095306/172049977-f9a45449-b805-4f40-91b6-4af56693e62b.png)

Shows follwoing message and unable to import

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by slaouist** [comment]
@last72 Thanks for reporting. We will look into it and get back to you as soon as possible.

**Comment by denisem-msft** [comment]
@last72 Is it possible for you to import the latest managed solution file to start using the kit? https://github.com/microsoft/powercat-creator-kit/releases/download/CreatorKit-June2022/CreatorKitCore_1.0.20220604.1_managed.zip

We were experimenting with distribution of both managed and unmanaged versions, but the recommended guidance from the Microsoft Solutions team is to use managed and then add components from the managed into your unmanaged dev solutions. Sorry for the confusion.

**Comment by denisem-msft** [comment]
@last72 can you please confirm if the latest version worked?

**Comment by denisem-msft** [comment]
Closing this issue - please reopen if needed.
