### ISSUE TITLE
[Creator Starter Kit] BUG: Left navigation panel is blank in the Creator Kit Reference App

### ISSUE THREAD

**Issue by swatibece** [microsoft/powercat-creator-kit#34]
**Describe the bug**
Not able to see left navigation panel content in the Creator Kit Reference App

**To Reproduce**
1. Go to the Solution - Creator Kit, or Go to the Apps list
2. Click on 'Play' on the app - Creator Kit Reference App
3. See below when the app is played, left navigation is blank
    
![image](https://user-images.githubusercontent.com/83767738/172129950-48e510e3-8753-4df0-8060-5bfab5447af5.png)

**Comment by denisem-msft** [comment]
@swatibece can you please confirm if you have enabled the Power Apps code components for canvas apps in the environment settings? Link to docs: https://docs.microsoft.com/en-us/power-apps/developer/component-framework/component-framework-for-canvas-apps#enable-the-power-apps-component-framework-feature

**Comment by swatibece** [comment]
Yes, I had PCF enabled, but I have now again deleted the solution, imported again and it looks fine, except for some of the controls like....dialog box or panel control under "Surfaces" . The complete screen is not visible and need to do Zoom to 80 to 70 %. Also, tried changing screen resolution. Not sure if it is the issue only with system though.
