### ISSUE TITLE
[BUG]: People Picker throws errors when blank

### ISSUE THREAD

**Issue by joneselliot** [microsoft/powercat-creator-kit#433]
Hi folks,

The People Picker control seems to have regressed since the last release. When the control is blank, it throws an error "JSON parsing error, expected 'array' but got 'undefined'. This prevents me from referencing the control when it is blank because of the downstream error effects. 

Furthermore, any IfError() attempts I make to mitigate this are ineffective - I even got the IfError function itself to throw an error... "Internal error in the IfError function: Core.ApplicationError: ConnectedDataQueryStringBuilderError Kind:8 Severity:3 JSON Parsing error, expected 'array' but got 'undefined'...". 

I really want to use this control, but this is making things tough :(

AB#1483

**Comment by MaheshSripada** [comment]
We haven’t heard back from you in a while. We’re closing this issue for now, but feel free to reopen it if you need further assistance.
