### ISSUE TITLE
[BUG]: Deploying the creator kit solution to GCCH is failing with "request is being redirected to the National Cloud 'MicrosoftOnline.COM"

### ISSUE THREAD

**Issue by rrwolfe** [microsoft/powercat-creator-kit#452]
**Describe the bug**
When attempting to import the creator kit solution in a GCC High environment, we're receiving the error below and unable to import the solution:

Solution "Creator Kit" failed to import: CanvasApp import: FAILURE: AADSTS90038: Tenant 'microsoftservices.onmicrosoft.com' request is being redirected to the National Cloud 'MicrosoftOnline.COM'

**To Reproduce**
**Note: This is when using a GCC High environment
1. Go to the Power Apps Maker Portal > Solutions
2. Click Import Solution
3. Select the Creator Kit managed solution file and click Import

**Expected behavior**
Solution imports successfully

**Screenshots**
![image](https://github.com/microsoft/powercat-creator-kit/assets/74214126/171ea887-f8d6-41e1-9de2-38dd4beb13c3)

AB#2504

**Comment by jwillisrose** [comment]
Plus one on this. Just had same error in a GCC-High tenant. 

Full error:

CanvasApp import: FAILURE: AADSTS90038: Tenant 'microsoftservices.onmicrosoft.com' request is being redirected to the National Cloud 'MicrosoftOnline.COM'. Trace ID: 3dee0c31-7bbb-48a2-926e-f0598b95f500 Correlation ID: 1f9158bc-6799-4967-a9d5-b8a3cd605aa0 Timestamp: 2024-03-08 19:13:22Z

**Comment by rrwolfe** [comment]
This issue was due to a platform bug that was resulting in failure of solution import/export for any solutions that contained canvas apps. This has now been resolved.

Message Center post: https://portal.office365.us/adminportal/home#/servicehealth/:/alerts/MX728869
