### ISSUE TITLE
[BUG]: Fluent Details List not sorting correctly

### ISSUE THREAD

**Issue by JimBD-dev** [microsoft/powercat-creator-kit#485]
**Describe the bug**
Since 24/07/2024 the Fluent Details List no longer shows the data as it is sorted by in the "Items" collection. 
The gallery used as a data source for the Details List, does sort correctly, but this no longer pulls through. 
This only happens in Authoring version v3.24073, reverting back to an earlier version fixes the problem.

A warning message also pops app when opening the app in Edit mode, see below.

![Warning_message](https://github.com/user-attachments/assets/26bbf212-f02f-4abf-bab1-0b0c3761af67)

AB#3895

**Comment by OliverDumrique** [comment]
Hi, we are aware of this issue impacting the sorting order of datasets in controls such as the Details List and are working to deploy a fix soon. In the meantime, please revert back to Canvas studio version v3.24072 (by appending "&studio-version=v3.24072.6.302069373" to the studio URL) to fix this issue.

You can refer to this known issue for live updates as the fix deploys. https://admin.powerplatform.microsoft.com/knownissues/4238060

**Comment by OliverDumrique** [comment]
The fix has been deployed, please verify and close the bug when you can.

**Comment by JimBD-dev** [comment]
Can you please verify what has been fixed, the Creator Kit or Power Apps, as far as I can see nothing has changed. 
![image](https://github.com/user-attachments/assets/d559ccf2-ff0d-4113-a2af-aa11ff439b30)
