### ISSUE TITLE
[BUG]: FluentDetailsList not showing formula fields when using AddColumns to Dataverse datasource

### ISSUE THREAD

**Issue by spgucken87** [microsoft/powercat-creator-kit#496]
**Describe the bug**
If using AddColumns in the Items property of a FluentDetailsList any formula columns in the Dataverse datasource will all be null/blank in the DetailsList. 

**To Reproduce**

1. Add formula fields to a FluentDetailsList
2. In the Items property utilize AddColumns function
3. Observe your formula fields show blank in the DetailsList

**Expected behavior**
Expect that the formula fields show as they would without using the AddColumns function

**Screenshots**
![image](https://github.com/user-attachments/assets/46a44b5f-4c89-4d10-8cc5-1b57bee3918c)
![image](https://github.com/user-attachments/assets/134d0a0b-001b-4e9d-a24b-a06eea4ccf79)
![image](https://github.com/user-attachments/assets/b3818b11-29fd-4e0c-ba6d-0a8e6e7ee8f0)

**Additional context**

**Comment by MaheshSripada** [comment]
Hi @spgucken87,

We appreciate you bringing this to our attention. 

Unfortunately we are unable to reproduce this issue in our environment by using collection with AddColumns using Dataverse datasource. Tried in OnVisible, App.Start and App.Formulas and by changing the Power Apps studio version. 

But I have faced this issue when I gave the incorrect / misspelt column name in the Columns property for the TagColorColumn where the color is not rendered correctly (as shown in above screenshot)


![image](https://github.com/user-attachments/assets/954848b3-11cc-4933-bc82-a83c48244489)
![image](https://github.com/user-attachments/assets/338d3296-9a26-4618-814f-d3f30698013d)
![image](https://github.com/user-attachments/assets/79cd5f00-438a-4aa3-804e-56856263b7b9)

Please provide any additional details which might help us troubleshoot further.

**Comment by MaheshSripada** [comment]
Hi @spgucken87,

Pls use the color format in the rgb format for the color in the PowerFx formula.  Example formula in below screenshot.

![image](https://github.com/user-attachments/assets/ed460a8e-6c7a-44d5-a8a9-2b8717f2ffe8)

**Comment by spgucken87** [comment]
I am unsure why you are stuck on the color. Any formula column does not show data on the details list if AddColumns is used. I was just using that color as an example, if I were to add ideal_statuscolor as a separate text column on the details list the same behavior happens. 

![image](https://github.com/user-attachments/assets/9d8a7872-766d-4354-94a3-7297d500bfcc)
![image](https://github.com/user-attachments/assets/3261ebbf-544e-484a-be37-7d422f164a75)

**Comment by MaheshSripada** [comment]
Hi @spgucken87,

Sorry for the inconvenience caused. I have also used the AddColumns with Formula column which is displaying the data in the details list for the formula column.

Screenshot of Items & Columns property.

![image](https://github.com/user-attachments/assets/d833e667-e1f4-459c-b8b3-98e0a97ceaa8)
 
![image](https://github.com/user-attachments/assets/34818749-3106-4374-a2f6-5124b8357b46)

![image](https://github.com/user-attachments/assets/3c5c6926-f7e5-4206-94f0-e164e51b880a)
