### ISSUE TITLE
[BUG]: Dialog OnButtonSelect property expecting record value

### ISSUE THREAD

**Issue by packman83** [microsoft/powercat-creator-kit#498]
**Describe the bug**
The OnButtonSelect property of the Dialog component no longer accepts IF statements or UpdateContext to be used. An error occurs that the property is expecting a record value.

**To Reproduce**
1. Add Dialog component to canvas
2. Configure OnButtonSelect property with the following code per the documentation
 `If( Self.SelectedButton.Label = "Close", 
        Notify("Email Sent")
    );
    UpdateContext({ showHideDialog: false })`
3. Error displayed for 'Expected Record Value'

**Expected behavior**
Configuring a Dialog OnButtonSelect property with IF statements and/or UpdateContext should work successfully

**Screenshots**
![image](https://github.com/user-attachments/assets/a1ae1b56-49f5-46bd-8eb7-94d6fe403674)

**Comment by jean-goyat** [comment]
@packman83, this is probably related to the way _component behavior property return type checks_ are now enforced by default. This is not a CreatorKit issue per say and as of yet I don't have an opinion regarding the expected return type of those OnSelect Dialog parameters... just wanted to point out a potential solution:

As a temporary measure, you can disable that check in the "retired" feature settings:
![image](https://github.com/user-attachments/assets/f5048b8c-fe48-441b-bb47-70343de7982b)

**Comment by packman83** [comment]
@jean-goyat, you are correct. I did not see that this is enforced by default now. Your suggestion to disable that check did the trick as a workaround for now.

Seeing as this is not a Creator Kit bug, marked as closed.
