### ISSUE TITLE
[Feature] Drag and Drop File Uploader

### ISSUE THREAD

**Issue by mallorylawhorne** [microsoft/powercat-creator-kit#58]
New Component

Drag and Drop File Uploader
Ability to update File Upload area to Drag and Drop area where you can simply... drag and drop the files you want to attach, then review what you have selected for import, then import. The current process is too many clicks and clunky (per my end users).

Similar in use to: https://www.npmjs.com/package/react-drag-drop-files

**Comment by denisem-msft** [comment]
Thanks for your feedback @mallorylawhorne. File upload is definitely a common scenario, but we do not have a specific experience or component in Fluent UI framework for a drag and drop or upload experience.

Have you tried using any of the community [drag and drop code components in pcf.gallery](https://pcf.gallery/categories#drag%20and%20drop)?

**Comment by ArtKarp** [comment]
You might also check out these code components from the PCfGallery...

https://pcf.gallery/categories#upload
