### ISSUE TITLE
[Feature] Change font size

### ISSUE THREAD

**Issue by yingying96** [microsoft/powercat-creator-kit#62]
Hi Team,

Thanks for the creator kit. May i know if it is possible to have a custom font size to change? Currently we can only change to either normal or large.

![image](https://user-images.githubusercontent.com/19566726/178428828-bab62f11-cb39-4faa-af2a-d21173bcdd53.png)

**Comment by slaouist** [comment]
Thanks for your question. We are following Fluent UI design language recomendation and using existing components that do not support font size changes.  So unfortonatly, there is no way to change font sizes in current implenentation.
