### ISSUE TITLE
[Feature] Reset Property for CheckBox

### ISSUE THREAD

**Issue by jordanbardwell** [microsoft/powercat-creator-kit#63]
**Is this request for a new component, or additional functionality for an existing component? **

additional functionality

**Have you validated that your desired feature or component is not already in the [backlog](https://github.com/microsoft/powercat-creator-kit/issues?q=is%3Aopen+is%3Aissue+label%3Abacklog)?**

Yes

**Describe the component and functionality you would like to see in the starter kit**

There is no way to reset the value with the checkbox you have provided, therefore the checkbox does not work very well in galleries.

**Describe alternatives you've considered**

**Additional context**

If you use the checkbox in a gallery, there is no way to reset the value after let's say a submission was made. When you come back to that gallery, whatever you checked is still checked.

**Comment by denisem-msft** [comment]
@jordanbardwell please try implementing the Set Row Selection functionality and let us know if that works: https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/detailslist#set-row-selection

**Comment by denisem-msft** [comment]
Closing this item due to inactivity. Please reopen if this is still an issue that needs to escalate.
