### ISSUE TITLE
[Feature] Ability to configure whether toggle closes upon click or not

### ISSUE THREAD

**Issue by denise-msft** [microsoft/powercat-creator-kit#69]
**Is this request for a new component, or additional functionality for an existing component? **
Existing - ContextMenu & CommandBar

**Have you validated that your desired feature or component is not already in the [backlog](https://github.com/microsoft/powercat-creator-kit/issues?q=is%3Aopen+is%3Aissue+label%3Abacklog)?**
Yes

**Describe the component and functionality you would like to see in the starter kit**
Some users might want the ability to choose if the toggle action (which is happening onSelect) will close the submenu that the toggle is found on.

![image](https://user-images.githubusercontent.com/43950360/179270694-32b0d1a8-3144-41af-a94e-31c590ebc777.png)

(Reported by Mike during internal Bug Bash July 2022)

**Comment by mikefactorial** [comment]
@denise-msft This has been fixed in the latest release.
