### ISSUE TITLE
[Feature] All property names should have full display names

### ISSUE THREAD

**Issue by denisem-msft** [microsoft/powercat-creator-kit#70]
For DetailsList properties, it would be nice to have property names with full names for accessibility

![image](https://user-images.githubusercontent.com/43950360/179272531-cfcd3986-f0ee-4400-bfcb-19dbdcba7507.png)

(Reported by Brian during internal Bug Bash July 2022)

**Comment by scottdurow** [comment]
The property dropdown seems to show only the schema names - and not the display names. 
E.g. In the properties panel, the columns dataset is shown as the display name:
![image](https://user-images.githubusercontent.com/2871121/179283906-516053a8-35fa-450a-9baa-8ed48d952642.png)

but in the properties drop down it is the schema name, and the tooltip is also the schema name.

![image](https://user-images.githubusercontent.com/2871121/179284384-6bad0a36-abe6-4a51-be91-985d1c4cd71c.png)

So unless anyone knows of a way to show the display names, I think this item can be closed as 'requires platform change'

**Comment by slaouist** [comment]
Requires platform change
