### ISSUE TITLE
[BUG]: DetailsList loads data slowly in Canvas app for large datasets 

### ISSUE THREAD

**Issue by denisem-msft** [microsoft/powercat-creator-kit#71]
**Describe the bug**
DetailsList in canvas apps loads slowly for large page sizes

**To Reproduce**
1. Setup DetailsList with large data set (>500 records)
2. Enable Large Dataset paging
3. Set Page size to 1000
4. Scroll to the bottom of the page quickly
5. Data does not load immediately (takes at least 5 seconds)

**Expected behavior**
Expect speed of custom pages, where data is loaded immediately

(Reported by Brian during internal Bug Bash July 2022)

**Comment by scottdurow** [comment]
Is this specific to canvas apps - so the same data and control configuration is slow in canvas apps - but fast when the DetailsList is included in a custom page?

**Comment by scottdurow** [comment]
Can you check that this is not caused by 'Scale to fit' being turned on. The DetailsList requires that Scale to fit be turned off under **Settings** -> **Display**
![image](https://user-images.githubusercontent.com/2871121/179282983-765f76e6-97d5-4695-b8a8-c5b88fb6c7f4.png)

**Comment by scottdurow** [comment]
@denisem-msft I suggest we close this due to inactivity - we can re-open if needed.
