### ISSUE TITLE
[Feature] Default & Reset Properties for the SearchBox

### ISSUE THREAD

**Issue by jean-goyat** [microsoft/powercat-creator-kit#78]
**Is this request for a new component, or additional functionality for an existing component?**
 additional functionality for an existing component

**Have you validated that your desired feature or component is not already in the [backlog](https://github.com/microsoft/powercat-creator-kit/issues?q=is%3Aopen+is%3Aissue+label%3Abacklog)?**
yes

**Describe the component and functionality you would like to see in the starter kit**
- Ability to set the default value of the _SearchBox_  (either from a variable or hard coded).
- Ability to reset the _SearchBox_ to its default value by calling a "**Reset()**" or updating the variable associated with it's _Default_ property

**Describe alternatives you've considered**
No current alternatives that I can think of, currently the only way to reset the control is to select & delete the text in the _SearchBox_

**Additional context**
![image](https://user-images.githubusercontent.com/50023372/181602071-c342db50-98ef-4257-8d57-2f4e88a5e938.png)

**Comment by slaouist** [comment]
This was addressed in the previous release. We added default value to the control but we can't have a Reset() function as the canvas components infrastructure does not have a mechanism to achieve that.
