### ISSUE TITLE
[Feature] Ability to change the text size on the DetailsList Control

### ISSUE THREAD

**Issue by daniel-alifano** [microsoft/powercat-creator-kit#81]
**Is this request for a new component, or additional functionality for an existing component? **
Additional Functionality to existing control

**Have you validated that your desired feature or component is not already in the [backlog]
Yes

**Describe the component and functionality you would like to see in the starter kit**
A font size property for the component to allow the font size to be changed

**Describe alternatives you've considered**
Only option would be to make the component larger, but not applicable for my project

**Comment by matteoparlato** [comment]
Hi all,
I see that this issue has been closed but as of today we can't change font size in DetailsList control. Is there any news about this?
Thanks
