### ISSUE TITLE
[BUG]: DetailsList allows for sort via Column headers via dataverse but not using sharepoint

### ISSUE THREAD

**Issue by daniel-alifano** [microsoft/powercat-creator-kit#82]
**Describe the bug**
With a datasource of Dataverse, clicking the header sorts the data based on that selection. However using a sharepoint datasource the sort functionality doesnt not work

**To Reproduce**
1. Add the DetailsList Component with sharepoint list as Datasource
2. Add ColSortable: true, to column in the column items property
3. Select column header

**Expected behavior**
Match functionality when using dataverse backend

**Desktop (please complete the following information):**
 Browser windows 10, chrome

**Comment by Ramakrishnan24689** [comment]
Hi @daniel-alifano,

Thanks for reaching out and helping with creator kit.

Detail list does support sorting irrespective of the data source. For Data source other than Dataverse, e.g. SharePoint, Manual Sorting needs to be performed.

Kindly refer below documentation on how to perform manual sorting.

https://github.com/microsoft/powercat-code-components/tree/main/DetailsList#manual-sorting

Adding steps below for quick reference.

Example - Steps to perform manual sort for SharePoint list.

1) In the **OnChange** property of details list, identifying "Sort" event and updating context of the column to be sorted along with sorting direction(Ascending or descending). 

```
If(Self.EventName="Sort", 
UpdateContext({
                ctxSortCol:Self.SortEventColumn,
                ctxSortAsc:If(Self.SortEventDirection='PowerCAT.FluentDetailsList.SortEventDirection'.Ascending,true,false)
 })
);
```

2) **CurrentSortColumn** property need to be set to variable holding column name
```ctxSortCol```

3) Sorting direction to be defined, by setting **CurrentSortDirection** property.

```
If(ctxSortAsc,
    'PowerCAT.FluentDetailsList.CurrentSortDirection'.Ascending,
    'PowerCAT.FluentDetailsList.CurrentSortDirection'.Descending) 
```

4) Applying the sort on input **Items** property
```
SortByColumns('Your SharePoint List',ctxSortCol,If(ctxSortAsc,SortOrder.Ascending,SortOrder.Descending))
```

**Comment by daniel-alifano** [comment]
This worked perfectly. Thanks for you help
