### ISSUE TITLE
[BUG]: Empty detail list

### ISSUE THREAD

**Issue by yingying96** [microsoft/powercat-creator-kit#83]
**Describe the bug**
Empty detail list
![image](https://user-images.githubusercontent.com/19566726/183294198-574dd027-18f4-4ae7-adb3-0c06c12ba419.png)

**To Reproduce**
1. Add fluent detail list
2. Connect to sharepoint datasource

**Expected behavior**
List of files from the connected datasource

**Screenshots**

**Desktop (please complete the following information):**
 - Chrome Browser
 - Version 100+

Creator Kit Version: 1.0.20220604.1

**Comment by daniel-alifano** [comment]
Have you added the columns to fields
![image](https://user-images.githubusercontent.com/31948694/183347955-3808b628-5213-450c-b17d-8d39cdfeb8c1.png)

Also adding them into column_items:

Table(
{ColName:"Request ID",ColDisplayName:"Request ID",ColWidth:125,ColSortable:true,ColResizable:true,ColRowHeader:true},
{ColName:"Title",ColDisplayName:"Title",ColWidth:200,ColSortable:true,ColResizable:true,ColRowHeader:true}
)

**Comment by yingying96** [comment]
Hello thanks for checking. Yes i think the fields are added?

![image](https://user-images.githubusercontent.com/19566726/183690166-56e945e6-f100-4506-bd5a-15042bf8bbdc.png)

**Comment by scottdurow** [comment]
Hi @yingying96 - from your screenshot above it looks like you have the Documents dataset bound to both the `Items` and the `Columns` properties. 

As @daniel-alifano says above, you'll need to define the column layout (display name, width, sortability etc.) in the `Columns` dataset. For more info see https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/detailslist#columns-table-schema

Hope this helps, and thank you for helping with the Creator Kit!

**Comment by yingying96** [comment]
Found it! Thank you both! 

![Uploading image.png…]()
