### ISSUE TITLE
[BUG]: Tag and Indicator Tag Column borders not always rendering properly.

### ISSUE THREAD

**Issue by sperry1625** [microsoft/powercat-creator-kit#86]
For Tag and IndicatorTag column types, box borders not always rendering correctly.

**To Reproduce**
1. Go to Add column with `ColCellType` of `"tag"` and/or `"indicatortag"`.
2. Add color options, `ColTagColorColumn`, `ColTagBorderColorColumn`
3. Have dataset with a few rows

**Expected behavior**
All tag items have all 4 borders

**Screenshots**
![image](https://user-images.githubusercontent.com/22748990/185205142-9f364ec3-d225-4fdb-8766-60e13d9d5e78.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 104.0.1293.54 (Official build) (64-bit)

**Additional context**

**Comment by scottdurow** [comment]
Hi @sperry1625 - thank you for reporting this and the detailed screenshots - it really helps. Whilst this is addressed, can you try using the workaround of adding the `ColPaddingTop` property to the Tag column to add some extra spacing?

**Comment by sperry1625** [comment]
I noticed something new today. I am working on a different monitor and the borders are rendering correctly (without the `ColPaddingTop` property). I also added the `ColPaddingTop` with an entry of 1. When I am working on the other monitor again I will see if that fixes the issue.

I hope the additional information helps.

**Regards,**

Steven

**Comment by scottdurow** [comment]
Thanks for the additional info. I suspect that it's to do with dpi and a rounding issue.

**Comment by denisem-msft** [comment]
Closing this for now as others have not reported this. Please feel free to re-open if this persists after Scott's suggestion to add padding.
