### ISSUE TITLE
[BUG]: Indicator Column Borders Color not Honored

### ISSUE THREAD

**Issue by sperry1625** [microsoft/powercat-creator-kit#88]
**Describe the bug**
Setting `ColTagBorderColorColumn` for an Indicator Tag column Does not set the border color.

**To Reproduce**
1. Add column to dataset that holds the border color (ex. "`rgba( 189, 0, 0, 1 )`") Call it "`MaintBorderColor`"
2. Add `ColTabBorcerColorColumn` to `columns_Items` dataset for a column.
3. Set that column `ColCellType` to "`indicatortag`"

**Expected behavior**
Border color to change to color specified in data column, `rgba( 189, 0, 0, 1 )`.

**Screenshots**
![image](https://user-images.githubusercontent.com/22748990/185213251-f02ade5d-62a3-4f83-9180-e36dc271cb8a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: Version 104.0.1293.54 (Official build) (64-bit)

**Additional context**
The color I am trying to set varies based on the row state, sometimes invisible. I tried `rgb( 0, 0, 0, 0 )` to remove the border, it works on the tag column type, but seems to have no effect on the `indicatortag` column type. No color I select changes the Border color.

**Comment by sperry1625** [comment]
The `ColTagColorColumn` changes the color for the indicator in front of the cell content. For the Tag cell type it sets the background color for the bounding box around the content. Is there a separate property for setting the background for an Indicator Tag cell? Can the bounding box be removed all together and just leave the indicator?

Should this move from a Bug to a Feature request?

**Regards,**

Steven

**Comment by scottdurow** [comment]
Hi @sperry1625 - Thank you for the additional info. You are right that the Tag cell type doesn't have a background color - it only has the indicator circle color. If `ColTagBorderColorColumn` could be used to define the border color - it could be set to transparent to hide it. Would this work for you?

**Comment by sperry1625** [comment]
Partly.  See below screenshots. 

![image](https://user-images.githubusercontent.com/22748990/185450080-22a5d861-b173-4e3e-862d-9305a3ae4f99.png)

And

![image](https://user-images.githubusercontent.com/22748990/185450117-f5b3231d-b6f3-4d82-bdfd-c5b504196809.png)

**Comment by denisem-msft** [comment]
@sperry1625 Is this still a requirement you could use, or can we close this?

**Comment by mikefactorial** [comment]
@sperry1625 This has been fixed in the latest release.
