### ISSUE TITLE
[BUG]:DETAILS LIST cant sort 

### ISSUE THREAD

**Issue by teslachina** [microsoft/powercat-creator-kit#89]
**Describe the bug**
![WX20220822-142544](https://user-images.githubusercontent.com/103990999/185853323-f9034a27-1aae-4b39-af6b-aded23b1d7cb.png)
In the editor's browse mode, you can already see that the system has used id for reverse sorting.
However, in the actual display, the sorting is invalid.

![image](https://user-images.githubusercontent.com/103990999/185853498-e65284a5-ea88-4170-80d0-e3675ffdbb6b.png)
I didn't make any other settings either.

thanks～

**Comment by teslachina** [comment]
@slaouist

**Comment by scottdurow** [comment]
Hi @teslachina - Thanks for posting this. I have identified an issue with PCF components being bound directly to SharePoint lists, where the sorting is not happening correctly.
The workaround is to wrap your items data source in `AddColumns` which converts it to a collection - you can  also use the manual sorting technique described here if you want dynamic sorting - https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/detailslist#manual-sorting

So in your case you would update your Items property to:
```
AddColumns(Sort(<YourDataSource>,cr87e_id,Descending),"SomeColumn","Value")
```

**Comment by denisem-msft** [comment]
We're able to reproduce this issue and will bring it to the PCF engineering team's attention

**Comment by teslachina** [comment]
Thanks～ @scottdurow
