### ISSUE TITLE
[BUG]: (MDA Reference App/Tag Picker Page) Custom styles container does not auto grow

### ISSUE THREAD

**Issue by scottdurow** [microsoft/powercat-creator-kit#98]
**Describe the bug**
Related to #97, however once that is fixed, the height of `Example2ContentContainer` needs to add `Picker1.AutoHeight`

**To Reproduce**
1. Open the Tag Picker custom page (once #97 is fixed)
2. Add colored tags in the 'custom styles' picker until the height increases
3. Notice that the container does not grow to accommodate the new height

**Comment by denisem-msft** [comment]
This has been fixed and will be available in the next release.
