### ISSUE TITLE
[BUG]: (MDA Reference App/Resizable Text Area Page) Styles container does not respond to height changes

### ISSUE THREAD

**Issue by scottdurow** [microsoft/powercat-creator-kit#99]
**Describe the bug**
When the text area is resized inside the Styles container, the following controls (Text, Contain, Allow spell check etc.) do not move with the new height like they do in the canvas reference app. The position of the controls should use the `ResizedHeight` property.

This also happens for the last sample on the page.

**To Reproduce**
1. Open the MDA Reference App
2. Navigate to the Resizable Text Area page
3. Resize the text area so that it grows in height

**Expected behavior**
The controls should move down to accommodate the new height like they do in the canvas reference app. Currently, the resize handle is clipped and so you cannot resize anymore:

**Screenshots**
![image](https://user-images.githubusercontent.com/2871121/188997705-4a50c886-cf02-458a-8a75-0075077e63a4.png)

**Comment by slaouist** [comment]
@scottdurow. This is fixed now. It be included the October release
